# Generated by Django 4.2.16 on 2026-05-29 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('actividad_economica', models.CharField(default='620100', max_length=255)),
                ('codigo_sin', models.CharField(default='99100', max_length=20)),
                ('codigo_producto', models.CharField(blank=True, max_length=20)),
                ('unidad_medida', models.IntegerField(default=62)),
                ('is_active', models.BooleanField(default=True)),
                ('tiene_pdf_automatico', models.BooleanField(default=False)),
                ('tipo_certificado', models.CharField(choices=[('baja_iimm', 'No haber sido dado de baja II.MM.'), ('titulo_grado', 'Título de Grado'), ('diplomado', 'Diplomado de Profesorado'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.department')),
            ],
        ),
    ]
